# Generated by Django 5.2.4 on 2025-07-29 15:10
from django.db import migrations

def add_categories(apps, schema_editor):
    Category = apps.get_model('Todothesis', 'Category')
    categories = [
        'Environment',
        'Air',
        'Water',
        'Drought',
        'Land',
        'Urban/Non Urban',
        'Biodiversity',
    ]
    for name in categories:
        Category.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('Todothesis', '0001_initial'),  # or whatever your last migration is
    ]

    operations = [
        migrations.RunPython(add_categories),
    ]
