# Generated by Django 5.2.4 on 2025-07-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todothesis', '0002_add_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressupdate',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
